name = "ETR Transfer Content"
prefix = "etr_transfer"
author = "European Tactical Realism"

[properties]
author = "European Tactical Realism"
url = "https://tacticalrealism.eu/"

[version]
git_hash = 0

[files]
include = []
exclude = [
    "*.psd",
    "*.png",
]

[hemtt.release]
archive = false